/* ============================================================
   AutóTanács — TÍPUSAJÁNLÓ katalógus
   ------------------------------------------------------------
   Ez a fájl azt tudja, hogy MELYIK autót érdemes megvenni —
   nem általánosságban, hanem konkrét motorral és évjárattal,
   adott keretösszegre.

   Egy bejegyzés = egy modellgeneráció. A `picks` tömb tartalmazza
   a valóban ajánlott konfigurációkat: motor + évjárat + váltó +
   mai magyar piaci ár. Az ajánló SOHA nem ajánl olyan darabot,
   aminek a `price[0]`-ja nem fér bele a megadott keretbe.

   Pontszámok 1–5 skálán (5 = a legjobb):
     rel     megbízhatóság
     run     fenntartási költség (5 = olcsó)
     comfort utazókényelem
     space   tér és csomagtartó
   A `fit` az egyes használati módokhoz való illeszkedés.

   Az árak 2026-os magyar használtpiaci BECSLÉSEK, tájékoztató
   jelleggel. A konkrét darab állapota ennél többet számít.
   ============================================================ */

const KB_CARS = [
  /* ==================== 1–2,5 M Ft — az olcsó sáv ==================== */
  {
    id: "swift2",
    name: "Suzuki Swift (2005–2010)",
    brand: "Suzuki", model: "Swift",
    years: [2005, 2010], body: ["Ferdehátú"], seats: 5, klass: "kisautó",
    picks: [
      { label: "1.3 benzin, 2007–2010, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [1100000, 1800000], km: "150–250 e km",
        why: "Láncos vezérlés (nincs szíjcsere-határidő), egyszerű szívómotor, ami 300 e km-t is elmegy alap karbantartással." },
    ],
    why: [
      "Ez az a kategória, ahol a legkevesebbet lehet hibázni: nincs turbó, nincs DPF, nincs kettőstömegű lendkerék, nincs bonyolult elektronika.",
      "Magyarországon rengeteg fut belőle, ezért az alkatrész olcsó és bármelyik szerelő ismeri.",
      "Kifejezetten jó első autónak: olcsó a biztosítás, olcsó a javítás, és ha összekarcolod, nem fáj.",
    ],
    watch: [
      "A hátsó kerékjárat és a küszöb rozsdásodik — ez a típus fő gyengéje. Emeld fel és nézd meg alulról.",
      "A kormánymű kopoghat; próbaút közben figyeld a kormányból visszaadó ütést.",
    ],
    avoid: ["1.3 DDiS dízel — ebbe a kategóriába és ilyen árban a dízel csak plusz kockázat."],
    fit: { városi: 5, hosszútáv: 2, vegyes: 4, család: 2, első: 5 },
    s: { rel: 4, run: 5, comfort: 2, space: 2 },
    tags: ["olcsó fenntartás", "első autó", "kis fogyasztás", "könnyű parkolás"],
  },
  {
    id: "yaris2",
    name: "Toyota Yaris II (2005–2011)",
    brand: "Toyota", model: "Yaris",
    years: [2005, 2011], body: ["Ferdehátú"], seats: 5, klass: "kisautó",
    picks: [
      { label: "1.0 vagy 1.3 VVT-i benzin, 2008–2011, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [1300000, 2100000], km: "150–250 e km",
        why: "A Toyota egyik legszívósabb kisbenzinese. Láncos vezérlés, alacsony fogyasztás, minimális meglepetés." },
    ],
    why: [
      "Ha a legfontosabb szempont az, hogy elinduljon minden reggel, ez a kategória etalonja.",
      "Meglepően tágas belül a mérethez képest, magas üléspozícióval — idősebb sofőrök is szeretik.",
      "A Toyota szervizháttér és az alkatrész-ellátás nálunk is stabil.",
    ],
    watch: [
      "Az elektromos szervokormány motorja hibásodhat meg — próbaúton figyeld, egyenletes-e a rásegítés.",
      "A 2006 előtti darabokon a hátsó futómű és a küszöb rozsdásodhat.",
    ],
    avoid: ["1.4 D-4D dízel ebben a méretben és árban — a DPF és az injektor felemészti a megtakarítást."],
    fit: { városi: 5, hosszútáv: 3, vegyes: 4, család: 2, első: 5 },
    s: { rel: 5, run: 5, comfort: 3, space: 2 },
    tags: ["olcsó fenntartás", "első autó", "megbízható", "kis fogyasztás"],
  },
  {
    id: "fabia2",
    name: "Škoda Fabia II (2007–2014)",
    brand: "Skoda", model: "Fabia",
    years: [2007, 2014], body: ["Ferdehátú", "Kombi"], seats: 5, klass: "kisautó",
    picks: [
      { label: "1.2 HTP 12V (70 LE) benzin, 2010–2014, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [1400000, 2300000], km: "130–220 e km",
        why: "Ez a régi, láncos szívómotor — NEM a bajos 1.2 TSI. Lassú, de olcsó és szívós." },
      { label: "1.6 TDI CR (75/90 LE), 2011–2014, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [1800000, 2700000], km: "180–280 e km",
        why: "Csak akkor, ha évi 20 000 km fölött jársz — akkor viszont nagyon gazdaságos." },
    ],
    why: [
      "A Fabia kombi ebben az árban kiugróan nagy csomagtartót ad — sok családnál kiváltja a nagyobb autót.",
      "VW-alapokra épül, de a Škoda-alkatrész olcsóbb; minden szerelő ismeri.",
      "Egyszerű, jól átlátható autó, amin nincs sok elromolható luxus.",
    ],
    watch: [
      "A 1.2 HTP-nél a vezérműlánc 150 e km felett nyúlhat — hidegindításkor csörgés az árulkodó jel.",
      "Az elektromos ablakemelő és a központi zár a típus visszatérő bosszúsága.",
    ],
    avoid: [
      "1.2 TSI (EA111) — ennél a motornál a láncfeszítő és az olajfogyás komoly kockázat.",
      "1.4 TDI három hengeres a korai darabokban — érdes és sokat javított motor.",
    ],
    fit: { városi: 5, hosszútáv: 3, vegyes: 4, család: 3, első: 5 },
    s: { rel: 4, run: 5, comfort: 3, space: 3 },
    tags: ["olcsó fenntartás", "első autó", "nagy csomagtartó", "kombi"],
  },
  {
    id: "astrah",
    name: "Opel Astra H (2004–2010)",
    brand: "Opel", model: "Astra",
    years: [2004, 2010], body: ["Ferdehátú", "Kombi"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "1.6 Twinport benzin, 2007–2010, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [1200000, 2000000], km: "170–260 e km",
        why: "Az olcsó, nagy autó receptje. Az alkatrész nevetségesen olcsó és mindenhol kapható." },
      { label: "1.7 CDTi (Isuzu, 100/110 LE), 2007–2010, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [1400000, 2200000], km: "200–300 e km",
        why: "Az Isuzu-eredetű dízel jó hírű és szívós — sokat futott darabok is elmennek még." },
    ],
    why: [
      "Ha nagy autó kell kevés pénzért, ez az egyik legjobb forint/méter arány a piacon.",
      "Rengeteg fut belőle, ezért bontóból is minden megvan, filléres áron.",
      "A kombi változat komoly pakolhatóságot ad családi ár alatt.",
    ],
    watch: [
      "Az Ecotec benzineseknél a vezérműlánc 120 e km felett nyúlik — hidegen hallgasd meg.",
      "A hátsó rugó eltörése és a fékcső átrozsdásodása visszatérő panasz.",
      "Az elektromos rendszer (CIM modul, kormánykerék-elektronika) tud rejtélyes hibákat produkálni.",
    ],
    avoid: ["1.9 CDTi 150 LE — szép erős, de az injektor és a turbó ebben az árban nagy tét.", "Easytronic robotizált váltó — az aktuátor javítása többe kerül, mint az autó fele."],
    fit: { városi: 4, hosszútáv: 4, vegyes: 4, család: 4, első: 4 },
    s: { rel: 3, run: 5, comfort: 3, space: 4 },
    tags: ["olcsó fenntartás", "nagy csomagtartó", "kombi", "sok pénzért nagy autó"],
  },
  {
    id: "jazz2",
    name: "Honda Jazz II (2008–2015)",
    brand: "Honda", model: "Jazz",
    years: [2008, 2015], body: ["Ferdehátú"], seats: 5, klass: "kisautó",
    picks: [
      { label: "1.2 vagy 1.4 i-VTEC benzin, 2010–2015, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [1900000, 3400000], km: "120–200 e km",
        why: "Láncos, szívó VTEC — a megbízhatóság iskolapéldája. A padlóba hajtható „mágikus ülés” miatt hihetetlenül pakolható." },
    ],
    why: [
      "A belső tere és a variálhatósága egy osztállyal nagyobb autót ver — a hátsó ülés padlóba süllyed, így szinte kisbuszként pakolható.",
      "A Honda szívómotorjai a legmegbízhatóbb benzinesek közé tartoznak; itt nincs turbó, ami elromolhat.",
      "Városban kiváló a kilátás és a fordulékonyság.",
    ],
    watch: [
      "A CVT automata változatot kerüld el, ha nincs dokumentált olajcsere-történet.",
      "A hátsó dobfék és a fékcsövek rozsdásodhatnak.",
    ],
    avoid: ["Hibrid (IMA) változat — az akkumulátorcsere aránytalanul drága ehhez az autóhoz képest."],
    fit: { városi: 5, hosszútáv: 3, vegyes: 4, család: 3, első: 5 },
    s: { rel: 5, run: 5, comfort: 3, space: 4 },
    tags: ["megbízható", "olcsó fenntartás", "pakolható", "első autó"],
  },
  {
    id: "picanto",
    name: "Kia Picanto / Hyundai i10 (2011–2020)",
    brand: "Kia", model: "Picanto",
    years: [2011, 2020], body: ["Ferdehátú"], seats: 5, klass: "városi kisautó",
    picks: [
      { label: "1.0 vagy 1.25 benzin, 2015–2019, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [2200000, 3600000], km: "60–140 e km",
        why: "Fiatal, keveset futott darabok is elérhetők ebben az árban — sok esetben még gyári garanciás szerviztörténettel." },
    ],
    why: [
      "Ebben az árban ez az egyik legfiatalabb, legkevesebbet futott autó, amit kaphatsz — és a kevés km többet ér, mint a nagy méret.",
      "A Kia 7 éves gyári garanciája miatt sok darabnak teljes, papírozott szerviztörténete van.",
      "Városi használatra és tanulásra ideális: átlátható méret, könnyű kormány, olcsó minden.",
    ],
    watch: [
      "Autópályán zajos és szeles — ha sokat jársz hosszú úton, ne ezt válaszd.",
      "A klíma és a hűtőrendszer kis alkatrészei tudnak szivárogni.",
    ],
    avoid: ["Automata (4 fokozatú) változat — fogyaszt és lassú; ebben az osztályban a manuális a jobb döntés."],
    fit: { városi: 5, hosszútáv: 1, vegyes: 3, család: 2, első: 5 },
    s: { rel: 4, run: 5, comfort: 2, space: 2 },
    tags: ["első autó", "olcsó fenntartás", "kis futás", "könnyű parkolás", "fiatal autó"],
  },

  /* ==================== 2,5–5 M Ft — a legnagyobb választék ==================== */
  {
    id: "octavia2",
    name: "Škoda Octavia II facelift (2009–2013)",
    brand: "Skoda", model: "Octavia",
    years: [2009, 2013], body: ["Sedan / Limuzin", "Kombi"], seats: 5, klass: "középkategória",
    picks: [
      { label: "1.6 TDI CR (105 LE), 2011–2013, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [2400000, 3600000], km: "200–320 e km",
        why: "A common rail 1.6 TDI a régi PD-nél jóval kulturáltabb és megbízhatóbb. 5 l/100 km körüli fogyasztás egy nagy autóban." },
      { label: "1.6 MPI (102 LE) szívó benzin, 2010–2013, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [2200000, 3300000], km: "150–260 e km",
        why: "Ha keveset jársz vagy csak városban: turbó nélküli szívómotor, ami lassú, de szinte elronthatatlan. Ez a jobb benzines választás itt, NEM a TSI." },
    ],
    why: [
      "Ez az autó a magyar használtpiac gerince: hatalmas csomagtartó, alacsony fogyasztás, filléres alkatrész.",
      "A kombi 580 literes csomagtartója költözésre, kutyára, biciklire is elég — SUV-ár nélkül.",
      "Minden szerelő ismeri, bontóból minden megvan; ez a hosszú távú fenntartás legfontosabb tényezője.",
    ],
    watch: [
      "A vezérműszíj a 1.6 TDI-nél kb. 180 e km — SZÁMLÁT kérj róla, ne szóbeli ígéretet.",
      "A DPF városi használatnál eltömődik; ha csak rövid utakra kell, ne dízelt válassz.",
      "A hátsó futómű szilentjei és a lengéscsillapítók 200 e km körül elfáradnak.",
    ],
    avoid: [
      "1.2 TSI és a korai 1.4 TSI (EA111) — láncfeszítő és olajfogyás.",
      "DSG7 (DQ200, száraz kuplungos) — városi használatban ez a leggyakoribb nagy számla.",
    ],
    fit: { városi: 3, hosszútáv: 5, vegyes: 5, család: 5, első: 3 },
    s: { rel: 4, run: 5, comfort: 4, space: 5 },
    tags: ["nagy csomagtartó", "kombi", "olcsó fenntartás", "hosszú táv", "család", "vontatás"],
  },
  {
    id: "auris2",
    name: "Toyota Auris II hibrid (2013–2018)",
    brand: "Toyota", model: "Auris",
    years: [2013, 2018], body: ["Ferdehátú", "Kombi"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "1.8 Hybrid (136 LE), 2015–2018, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [3900000, 5800000], km: "120–220 e km",
        why: "A Toyota hibrid hajtáslánca a piac egyik legmegbízhatóbb szerkezete: nincs kuplung, nincs váltó, nincs turbó, nincs DPF, és a fékek alig kopnak." },
    ],
    why: [
      "Ha városban vagy vegyesen jársz, ez a legolcsóbban fenntartható normális méretű autó: 4,5–5,5 l/100 km városban is.",
      "A hibrid hajtáslánc kevesebb kopó alkatrészt tartalmaz, mint egy hagyományos benzines — ezért öregszik ilyen jól.",
      "A kombi (Touring Sports) változat nagy csomagtartót ad hibrid fogyasztás mellett.",
    ],
    watch: [
      "Vásárlás előtt KÉRJ akkumulátor-egészség (SoH) mérést — 15 perc, és ez a legfontosabb adat ennél az autónál.",
      "A 12 voltos kisakku gyengülése rejtélyes elektromos hibákat okoz; olcsó tétel, de sokan elfelejtik.",
    ],
    avoid: ["1.4 D-4D dízel változat — az egyetlen gyenge motor a kínálatban."],
    fit: { városi: 5, hosszútáv: 4, vegyes: 5, család: 4, első: 4 },
    s: { rel: 5, run: 5, comfort: 4, space: 4 },
    tags: ["megbízható", "olcsó fenntartás", "hibrid", "kis fogyasztás", "automata", "város"],
  },
  {
    id: "prius3",
    name: "Toyota Prius III (2009–2015)",
    brand: "Toyota", model: "Prius",
    years: [2009, 2015], body: ["Ferdehátú"], seats: 5, klass: "középkategória",
    picks: [
      { label: "1.8 Hybrid (136 LE), 2012–2015, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [3400000, 5200000], km: "180–320 e km",
        why: "Taxiként milliós km-eket futott világszerte — ez a hajtáslánc bizonyított. A magas km itt kevésbé ijesztő, mint máshol." },
    ],
    why: [
      "A fenntartási költsége verhetetlen: nincs kuplung, nincs váltó, nincs vezérműszíj, és a fékbetét is örökké tart a rekuperáció miatt.",
      "Városi és vegyes használatban 4,5–5 l/100 km reális.",
      "Ha sokat állsz dugóban (futár, ügynök, város), ez a típus a matematikai válasz.",
    ],
    watch: [
      "SoH-mérés kötelező. A hajtásakkumulátor cseréje 400 e – 1,2 M Ft, de cellánként is javítható.",
      "A gen3 EGR-rendszere kokszosodik, és ez hengerfejtömítés-hibához vezethet — kérdezz rá az EGR-tisztításra.",
    ],
    avoid: ["Nagyon magas (350 e km feletti) km-es darab SoH-mérés nélkül."],
    fit: { városi: 5, hosszútáv: 4, vegyes: 5, család: 4, első: 3 },
    s: { rel: 5, run: 5, comfort: 4, space: 4 },
    tags: ["olcsó fenntartás", "hibrid", "kis fogyasztás", "automata", "sok km", "város"],
  },
  {
    id: "focus3",
    name: "Ford Focus III (2011–2018)",
    brand: "Ford", model: "Focus",
    years: [2011, 2018], body: ["Ferdehátú", "Kombi"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "1.6 TDCi (95/115 LE), 2013–2017, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [2600000, 4200000], km: "180–280 e km",
        why: "A PSA-eredetű 1.6 dízel gazdaságos; a fő kockázata (turbó olajcső) ismert és megelőzhető." },
    ],
    why: [
      "Az egyik legjobban vezethető autó a kategóriában — a futóműve komfortos és biztonságos egyszerre.",
      "A kombi jó méretű csomagtartót ad, és a típus ára reális, mert sok van belőle.",
      "Ha sokat jársz autópályán, a hosszútávú komfortja jobb, mint az árban lévő legtöbb riválisé.",
    ],
    watch: [
      "Az 1.6 TDCi turbójának olajcsöve elkokszolódik — kérdezz rá, cserélték-e a csövet és a szűrőt.",
      "A rögzítőfék-elektronika és a Bluetooth/SYNC modul tud bosszantó hibákat okozni.",
    ],
    avoid: [
      "PowerShift (DPS6) dupla kuplungos automata — ez a váltó a típus legrosszabb hírű alkatrésze, kerüld el.",
      "1.0 EcoBoost a 2017 előtti darabokban — hűtőrendszer és hengerfej-repedés kockázat.",
    ],
    fit: { városi: 4, hosszútáv: 5, vegyes: 5, család: 4, első: 3 },
    s: { rel: 3, run: 4, comfort: 4, space: 4 },
    tags: ["jó vezetés", "kombi", "hosszú táv", "kényelmes"],
  },
  {
    id: "ceed2",
    name: "Kia Ceed II / Hyundai i30 II (2012–2018)",
    brand: "Kia", model: "Ceed",
    years: [2012, 2018], body: ["Ferdehátú", "Kombi"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "1.4 vagy 1.6 CVVT benzin, 2014–2017, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [2900000, 4400000], km: "120–200 e km",
        why: "Szívó benzines, láncos vezérlés, minimális meglepetés — és sok darab még a 7 éves gyári garanciában szervizelt." },
    ],
    why: [
      "A 7 éves gyári garancia miatt ezeknél az autóknál sokkal gyakoribb a hiánytalan, papírozott szerviztörténet, mint a német riválisoknál.",
      "Egyszerű, jól összerakott autó, aminek a fenntartása kiszámítható.",
      "A kombi (Sportswagon) meglepően nagy csomagtartót ad.",
    ],
    watch: [
      "A hátsó lengéscsillapító és a futómű szilentjei 150 e km körül elfáradnak.",
      "A 1.6 CRDi dízelnél a DPF városban gyorsan eltömődik.",
    ],
    avoid: ["1.6 GDI benzin — szívószelep-kokszolódás és nagynyomású szivattyú kockázata, közvetlen befúvás miatt."],
    fit: { városi: 4, hosszútáv: 4, vegyes: 5, család: 4, első: 4 },
    s: { rel: 4, run: 4, comfort: 4, space: 4 },
    tags: ["megbízható", "papírozott szerviz", "kombi", "garancia"],
  },
  {
    id: "duster1",
    name: "Dacia Duster I (2010–2017)",
    brand: "Dacia", model: "Duster",
    years: [2010, 2017], body: ["SUV / Terepjáró"], seats: 5, klass: "kompakt SUV",
    picks: [
      { label: "1.5 dCi (110 LE), 2014–2017, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [2400000, 3900000], km: "150–250 e km",
        why: "A K9K dízel a Renault-csoport egyik legelterjedtebb, legolcsóbban javítható motorja." },
      { label: "1.6 16V benzin, 2013–2017, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [2200000, 3400000], km: "120–200 e km",
        why: "Ha keveset jársz: szívó benzines, olcsó alkatrésszel, DPF nélkül." },
    ],
    why: [
      "Ez a legolcsóbb út a magas üléspozícióhoz és a terepképes hasmagassághoz — dűlőúton, hóban, földúton tényleg elmegy.",
      "Szándékosan egyszerűre tervezték: kevés elektronika, kevés elromolható luxus, olcsó alkatrész.",
      "Az összkerekes (4x4) változat komoly képességet ad a kategória árához képest.",
    ],
    watch: [
      "A belső anyagminőség és a zajszigetelés gyenge — hosszú úton fárasztó lehet.",
      "A K9K turbójának olajellátása kritikus: kérdezz rá a rendszeres olajcserére.",
      "Az alváz és a kipufogó rozsdásodik; nézd meg alulról.",
    ],
    avoid: ["1.2 TCe benzin — a vezérműlánc ennél a motornál komoly kockázat."],
    fit: { városi: 3, hosszútáv: 3, vegyes: 5, család: 4, első: 3 },
    s: { rel: 4, run: 5, comfort: 2, space: 4 },
    tags: ["SUV", "terep", "hasmagasság", "olcsó fenntartás", "összkerék", "hó"],
  },
  {
    id: "mazda3bm",
    name: "Mazda 3 (2013–2018)",
    brand: "Mazda", model: "3",
    years: [2013, 2018], body: ["Ferdehátú", "Sedan / Limuzin"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "2.0 Skyactiv-G (120 LE), 2014–2018, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [3400000, 5200000], km: "100–190 e km",
        why: "Szívó benzines turbó nélkül, láncos vezérléssel — ma ritka és értékes kombináció. Kulturált, tartós, kevés meglepetés." },
    ],
    why: [
      "A Mazda szándékosan nem ment bele a kis turbós motorok divatjába: ez a szívó 2.0 sokkal kevesebbet romlik, mint a hasonló korú turbós riválisok.",
      "Az anyagminőség és a vezetési élmény egy kategóriával feljebb szól.",
      "Kevés van belőle a magyar piacon, ezért a jó darabok tovább tartják az értéküket.",
    ],
    watch: [
      "A Skyactiv-G szívószelepei kokszolódhatnak; a rendszeres olajcsere itt is a védelem.",
      "A hátsó kerékjárat és a küszöb korrózióvédelme nem a legerősebb — nézd meg alaposan.",
    ],
    avoid: ["2.2 Skyactiv-D dízel városi használatra — olajhígulás és DPF-gond a rövid utakon."],
    fit: { városi: 4, hosszútáv: 5, vegyes: 5, család: 3, első: 3 },
    s: { rel: 4, run: 4, comfort: 4, space: 3 },
    tags: ["megbízható", "jó vezetés", "szívó motor", "igényes belső"],
  },
  {
    id: "golf6",
    name: "Volkswagen Golf VI (2008–2012)",
    brand: "Volkswagen", model: "Golf",
    years: [2008, 2012], body: ["Ferdehátú", "Kombi"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "1.6 TDI CR (105 LE), 2010–2012, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [2500000, 3800000], km: "200–300 e km",
        why: "Kulturált, gazdaságos common rail dízel — a régi PD-motorok utáni nagy előrelépés." },
    ],
    why: [
      "Nagyon jól összerakott, csendes autó, ami sokkal drágábbnak érződik, mint amennyibe kerül.",
      "Óriási alkatrész-kínálat és minden szerelő ismeri.",
      "Jó kompromisszum méret, komfort és fogyasztás között.",
    ],
    watch: [
      "Vezérműszíj 180 e km körül — kérj számlát.",
      "A 2010 előtti darabokon a DPF és az EGR városi használatnál gyakori panasz.",
    ],
    avoid: [
      "1.2 / 1.4 TSI (EA111) — láncfeszítő és olajfogyás.",
      "DSG7 száraz kuplungos — városban ez a legdrágább hiba.",
    ],
    fit: { városi: 4, hosszútáv: 5, vegyes: 5, család: 4, első: 3 },
    s: { rel: 3, run: 4, comfort: 5, space: 3 },
    tags: ["kényelmes", "csendes", "hosszú táv", "jó anyagminőség"],
  },
  {
    id: "verso",
    name: "Toyota Verso (2009–2018)",
    brand: "Toyota", model: "Verso",
    years: [2009, 2018], body: ["Egyterű"], seats: 7, klass: "egyterű",
    picks: [
      { label: "1.8 Valvematic benzin, 2013–2017, manuális vagy CVT", fuel: "Benzin", gearbox: "Manuális",
        price: [3400000, 5400000], km: "130–230 e km",
        why: "Szívó benzines, láncos vezérlés — hét ülés úgy, hogy közben nem kell dízel-kockázatot vállalni." },
    ],
    why: [
      "Ha 5-nél többen vagytok, ez az egyik legmegbízhatóbb hét üléses választás a piacon.",
      "A két hátsó ülés a padlóba süllyed, így 5 személyes módban is teljes értékű csomagtér marad.",
      "Toyota-megbízhatóság egy olyan kategóriában, ahol a riválisok jellemzően bonyolult dízelek.",
    ],
    watch: [
      "A harmadik sor felnőttnek szűk — rövid útra jó, nyaralásra nem.",
      "A CVT automata változatnál kérdezz rá az olajcserére.",
    ],
    avoid: ["2.0 D-4D (2AD) dízel — hengerfej-problémás motor, kifejezetten kerülendő."],
    fit: { városi: 3, hosszútáv: 4, vegyes: 4, család: 5, első: 2 },
    s: { rel: 5, run: 4, comfort: 4, space: 5 },
    tags: ["7 ülés", "család", "nagy csomagtartó", "megbízható", "gyerek"],
  },

  /* ==================== 5–8 M Ft ==================== */
  {
    id: "octavia3",
    name: "Škoda Octavia III (2013–2020)",
    brand: "Skoda", model: "Octavia",
    years: [2013, 2020], body: ["Sedan / Limuzin", "Kombi"], seats: 5, klass: "középkategória",
    picks: [
      { label: "1.6 TDI CR EA288 (115 LE), 2017–2019, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [4600000, 6800000], km: "140–230 e km",
        why: "A 2015 utáni EA288 dízel a legkiforrottabb VW-dízel: kulturált, 4,5–5 l/100 km, és mentes a régi PD-motorok bajaitól." },
      { label: "1.5 TSI EA211 (150 LE), 2018–2020, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [5400000, 7600000], km: "80–160 e km",
        why: "Ha nem jársz sokat: erős, kulturált benzines DPF-gond nélkül. FIGYELEM: ennél SZÍJ van, nem lánc — a csere határidő." },
    ],
    why: [
      "A magyar piac legracionálisabb választása: hatalmas tér, alacsony fogyasztás, olcsó alkatrész, kiszámítható fenntartás.",
      "A kombi 610 literes csomagtartója a legtöbb SUV-ot megveri — miközben kevesebbet fogyaszt és olcsóbb a gumi.",
      "Ha vontatnál (utánfutó, lakókocsi), ez a típus erre gyárilag felkészített és bőven van hozzá vonóhorog.",
    ],
    watch: [
      "Vezérműszíj: az EA288 dízelnél kb. 180 e km, a 1.5 TSI-nél is SZÍJ van — mindkettőnél kérj számlát.",
      "Városi, rövid utas használatnál a dízel DPF-je eltömődik. Ha csak városban jársz, benzinest válassz.",
      "A hátsó futómű és a lengéscsillapítók 180 e km felett kopnak.",
    ],
    avoid: [
      "DSG7 (DQ200) száraz kuplungos váltó, ha sokat állsz dugóban.",
      "1.4 TSI a 2016 előtti darabokban — még az EA211 korai szériája.",
    ],
    fit: { városi: 3, hosszútáv: 5, vegyes: 5, család: 5, első: 3 },
    s: { rel: 4, run: 5, comfort: 4, space: 5 },
    tags: ["nagy csomagtartó", "kombi", "olcsó fenntartás", "hosszú táv", "család", "vontatás", "kutya"],
  },
  {
    id: "corolla12",
    name: "Toyota Corolla hibrid (2019–2023)",
    brand: "Toyota", model: "Corolla",
    years: [2019, 2023], body: ["Ferdehátú", "Kombi", "Sedan / Limuzin"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "1.8 Hybrid (122 LE), 2019–2021, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [7200000, 9800000], km: "60–150 e km",
        why: "A negyedik generációs Toyota-hibrid: kiforrott, csendes, és a szervizigénye minimális. Ez ma az egyik legkevesebb kockázatot hordozó használt autó." },
      { label: "2.0 Hybrid (184 LE), 2019–2021, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [8200000, 11000000], km: "60–140 e km",
        why: "Ha sokat jársz autópályán: erősebb, nyugodtabb, és alig fogyaszt többet." },
    ],
    why: [
      "Ha a legfontosabb szempont az, hogy ne kelljen szerelővel találkozni, ez ma a legjobb vétel a piacon.",
      "Nincs turbó, nincs DPF, nincs kuplung, nincs hagyományos váltó, nincs vezérműszíj — a tipikus nagy hibaforrások egyszerűen hiányoznak.",
      "5 l/100 km körüli reális fogyasztás vegyes használatban, egy teljes értékű családi autóban.",
      "A Touring Sports kombi ugyanezt adja nagy csomagtartóval.",
    ],
    watch: [
      "SoH-mérést itt is kérj, bár ilyen fiatalon még ritkán probléma.",
      "Sok darabon még él a Toyota Relax kiterjesztett garancia, ha márkaszervizben szervizelték — ez pénzben mérhető előny, kérdezz rá!",
    ],
    avoid: ["1.2 Turbo benzin változat — jó motor, de a hibrid mellett nincs értelme."],
    fit: { városi: 5, hosszútáv: 5, vegyes: 5, család: 5, első: 4 },
    s: { rel: 5, run: 5, comfort: 4, space: 4 },
    tags: ["megbízható", "hibrid", "olcsó fenntartás", "automata", "kis fogyasztás", "család", "garancia", "fiatal autó"],
  },
  {
    id: "rav4-4",
    name: "Toyota RAV4 IV (2013–2018)",
    brand: "Toyota", model: "RAV4",
    years: [2013, 2018], body: ["SUV / Terepjáró"], seats: 5, klass: "SUV",
    picks: [
      { label: "2.0 Valvematic benzin, 2015–2018, manuális vagy CVT", fuel: "Benzin", gearbox: "Manuális",
        price: [5400000, 7800000], km: "120–200 e km",
        why: "Szívó benzines, láncos vezérlés — SUV-méret a turbós motorok kockázata nélkül." },
      { label: "2.5 Hybrid AWD, 2016–2018, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [7200000, 9800000], km: "100–190 e km",
        why: "Összkerék + hibrid: télen biztonságos, mégis 6 l/100 km körül fogyaszt." },
    ],
    why: [
      "Nagy, magas, biztonságos családi autó olyan hajtáslánccal, ami hosszú távon is kiszámítható.",
      "A hibrid AWD változat elektromos hátsó tengelyt használ — nincs kardántengely és osztómű, ami elromolhat.",
      "A Toyota SUV-jai nálunk jól tartják az értéküket, tehát a pénzed nagy része megmarad.",
    ],
    watch: [
      "A nagy méret városban kényelmetlen; ha csak belvárosban parkolsz, gondold át.",
      "A hibridnél SoH-mérés, a benzinesnél a CVT olajcsere-történet a kérdés.",
    ],
    avoid: ["2.2 D-4D dízel — a 2AD motor hengerfej-problémái miatt ez a kínálat egyetlen gyenge pontja."],
    fit: { városi: 2, hosszútáv: 5, vegyes: 5, család: 5, első: 2 },
    s: { rel: 5, run: 4, comfort: 4, space: 5 },
    tags: ["SUV", "család", "összkerék", "hasmagasság", "megbízható", "hó", "nagy csomagtartó"],
  },
  {
    id: "sportage4",
    name: "Kia Sportage IV / Hyundai Tucson III (2015–2020)",
    brand: "Kia", model: "Sportage",
    years: [2015, 2020], body: ["SUV / Terepjáró"], seats: 5, klass: "SUV",
    picks: [
      { label: "1.6 GDI (132 LE) benzin, 2017–2019, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [5200000, 7400000], km: "80–160 e km",
        why: "Szívó közvetlen befúvású benzines turbó nélkül — a kínálat legkevesebb kockázatot hordozó motorja." },
      { label: "1.7 / 1.6 CRDi dízel, 2017–2019, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [5400000, 7600000], km: "120–200 e km",
        why: "Csak ha évi 20 000 km fölött és nem csak városban jársz." },
    ],
    why: [
      "A 7 éves gyári garancia miatt sok darab teljes, papírozott márkaszervizes múlttal érkezik — ez SUV-nál különösen sokat ér.",
      "Modern felszereltség (tolatókamera, sávtartó, tempomat) olyan áron, amiért a német riválisokban csak alapfelszereltséget kapsz.",
      "Kényelmes, tágas és jól használható családi autó.",
    ],
    watch: [
      "A dízel DPF-je városi használatban gyorsan eltömődik.",
      "A DCT dupla kuplungos automata változatnál kérdezz rá a kuplung állapotára.",
    ],
    avoid: ["1.6 T-GDI turbós benzin — szívószelep-kokszolódás és turbó-kockázat. A turbó nélküli, szívó változat a jobb vétel."],
    fit: { városi: 3, hosszútáv: 4, vegyes: 5, család: 5, első: 3 },
    s: { rel: 4, run: 4, comfort: 4, space: 5 },
    tags: ["SUV", "család", "hasmagasság", "garancia", "papírozott szerviz", "felszereltség"],
  },
  {
    id: "vitara2",
    name: "Suzuki Vitara (2015–2023)",
    brand: "Suzuki", model: "Vitara",
    years: [2015, 2023], body: ["SUV / Terepjáró"], seats: 5, klass: "kompakt SUV",
    picks: [
      { label: "1.6 benzin (120 LE), 2016–2018, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [4200000, 5800000], km: "80–160 e km",
        why: "Szívó, láncos benzinmotor: nincs turbó, nincs DPF, nincs vezérműszíj-határidő. Ennél egyszerűbb SUV nincs a piacon." },
      { label: "1.4 BoosterJet AllGrip, 2018–2021, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [5800000, 7800000], km: "60–130 e km",
        why: "Ha kell az összkerék: az AllGrip rendszer télen komoly előny, és a motor is elég erős hozzá." },
    ],
    why: [
      "Kis méret, magas üléspozíció — pont az a kombináció, amit sokan keresnek: SUV-előny városi méretben.",
      "Magyarországon gyártják (Esztergom), ezért az alkatrészellátás és a szervizháttér kifejezetten jó.",
      "A Suzuki szívómotorjai a legkevesebb bajt okozó benzinesek közé tartoznak.",
    ],
    watch: [
      "A belső anyagminőség nem prémium — sok a kemény műanyag.",
      "Autópályán a szélzaj magasabb, mint a nagyobb riválisoknál.",
    ],
    avoid: ["1.6 DDiS dízel — a DPF ebben a kis autóban aránytalanul nagy kockázat."],
    fit: { városi: 5, hosszútáv: 3, vegyes: 5, család: 4, első: 4 },
    s: { rel: 5, run: 5, comfort: 3, space: 3 },
    tags: ["SUV", "hasmagasság", "megbízható", "olcsó fenntartás", "összkerék", "könnyű parkolás", "hó"],
  },
  {
    id: "chr",
    name: "Toyota C-HR hibrid (2016–2023)",
    brand: "Toyota", model: "C-HR",
    years: [2016, 2023], body: ["SUV / Terepjáró"], seats: 5, klass: "kompakt SUV",
    picks: [
      { label: "1.8 Hybrid (122 LE), 2018–2021, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [6200000, 9200000], km: "70–160 e km",
        why: "Ugyanaz a bizonyított hibrid hajtáslánc, mint a Priusban és a Corollában — SUV-karosszériában." },
    ],
    why: [
      "Városi használatra ez az egyik legolcsóbban fenntartható SUV: 5 l/100 km körül megy, és a fékei alig kopnak.",
      "Feltűnő, karakteres formaterv — ha számít, hogy hogy néz ki az autód, ez kilóg a mezőnyből.",
      "Toyota-hibrid megbízhatóság, magasabb üléspozícióval.",
    ],
    watch: [
      "A hátsó utastér és a látótér szűk a lejtős tető és a kis hátsó ablakok miatt — üljetek bele hátra, mielőtt megveszed.",
      "A csomagtartó kisebb, mint a méret sugallja.",
    ],
    avoid: ["1.2 Turbo benzin változat — a hibrid mellett nincs értelme."],
    fit: { városi: 5, hosszútáv: 4, vegyes: 5, család: 3, első: 4 },
    s: { rel: 5, run: 5, comfort: 4, space: 3 },
    tags: ["SUV", "hibrid", "megbízható", "olcsó fenntartás", "automata", "város", "szép"],
  },
  {
    id: "superb3",
    name: "Škoda Superb III (2015–2023)",
    brand: "Skoda", model: "Superb",
    years: [2015, 2023], body: ["Sedan / Limuzin", "Kombi"], seats: 5, klass: "felső-közép",
    picks: [
      { label: "2.0 TDI EA288 (150 LE), 2017–2019, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [6200000, 8600000], km: "150–250 e km",
        why: "Nagy autó, kulturált dízel, 5,5 l/100 km autópályán. Ha sokat jársz hosszú úton, ez a matematikai válasz." },
    ],
    why: [
      "A hátsó lábtér nagyobb, mint sok luxusautóé — ha hátul is utaznak felnőttek, ez érezhető különbség.",
      "A kombi 660 literes csomagtartója gyakorlatilag kisbusz-kategória.",
      "Hosszú úton csendes és nyugodt; a fogyasztása mégis kompakt szinten marad.",
    ],
    watch: [
      "Városi használatra túl nagy és a dízel DPF-je is szenvedne — ez egy autópályás autó.",
      "A vezérműszíj (kb. 180 e km) és az adott darab szerviztörténete a döntő kérdés.",
    ],
    avoid: ["DSG7 száraz kuplungos változat ekkora tömeghez.", "1.4 TSI — kevés ehhez az autóhoz, és a fogyasztása sem lesz jobb."],
    fit: { városi: 2, hosszútáv: 5, vegyes: 4, család: 5, első: 1 },
    s: { rel: 4, run: 4, comfort: 5, space: 5 },
    tags: ["nagy csomagtartó", "kombi", "hosszú táv", "kényelmes", "család", "vontatás", "sok hely hátul"],
  },
  {
    id: "crv4",
    name: "Honda CR-V IV (2012–2018)",
    brand: "Honda", model: "CR-V",
    years: [2012, 2018], body: ["SUV / Terepjáró"], seats: 5, klass: "SUV",
    picks: [
      { label: "2.0 i-VTEC benzin, 2015–2018, manuális vagy automata", fuel: "Benzin", gearbox: "Manuális",
        price: [5400000, 7800000], km: "100–190 e km",
        why: "Szívó VTEC benzines, láncos vezérléssel — a Honda legmegbízhatóbb receptje egy nagy SUV-ban." },
    ],
    why: [
      "Tágas, praktikus és rendkívül tartós — ez az a SUV, amit tíz év múlva is lehet szeretni.",
      "A szívó benzines hajtás miatt nincs turbó, DPF vagy nagynyomású befúvás, ami elromolhatna.",
      "Kiváló kilátás és nagy csomagtartó.",
    ],
    watch: [
      "A 2.0 benzines fogyasztása városban magas (9–10 l/100 km) — vedd bele a számításba.",
      "Az összkerékhajtás hátsó differenciáljának olajcseréjére kérdezz rá.",
    ],
    avoid: ["1.6 i-DTEC dízel a korai darabokban — a DPF és az EGR városi használatnál problémás."],
    fit: { városi: 3, hosszútáv: 5, vegyes: 4, család: 5, első: 2 },
    s: { rel: 5, run: 3, comfort: 4, space: 5 },
    tags: ["SUV", "megbízható", "család", "nagy csomagtartó", "hasmagasság"],
  },
  {
    id: "leaf40",
    name: "Nissan Leaf 40 kWh (2018–2022)",
    brand: "Nissan", model: "Leaf",
    years: [2018, 2022], body: ["Ferdehátú"], seats: 5, klass: "elektromos",
    picks: [
      { label: "40 kWh elektromos (150 LE), 2018–2020", fuel: "Elektromos", gearbox: "Automata",
        price: [5200000, 7400000], km: "50–130 e km",
        why: "Reális 200–250 km hatótáv, olcsó belépő az elektromos autózásba. Városi és agglomerációs használatra bőven elég." },
    ],
    why: [
      "Ha van otthoni töltési lehetőséged és napi 100 km alatt jársz, a fenntartási költséged a töredékére esik: nincs olaj, nincs vezérműszíj, nincs kuplung, nincs kipufogó.",
      "A zöld rendszám kedvezményei (parkolás, adók) évi több százezer forintot érhetnek.",
      "Csendes, nyugodt és egyszerűen vezethető autó.",
    ],
    watch: [
      "SoH-mérés KÖTELEZŐ. A Leaf akkumulátora nem folyadékhűtött, ezért melegben és sok gyorstöltéstől gyorsabban öregszik, mint a riválisoké.",
      "Hosszú úton a gyorstöltés lelassul (ez az ismert „RapidGate\" jelenség) — ha sokat autópályázol, ez nem a te autód.",
    ],
    avoid: ["24 kWh-s korábbi generáció — a hatótávja ma már túl kevés, és az akkumulátora is öregebb."],
    fit: { városi: 5, hosszútáv: 1, vegyes: 3, család: 3, első: 3 },
    s: { rel: 4, run: 5, comfort: 4, space: 3 },
    tags: ["elektromos", "olcsó fenntartás", "város", "zöld rendszám", "automata", "csendes"],
  },

  /* ==================== 8–13 M Ft ==================== */
  {
    id: "octavia4",
    name: "Škoda Octavia IV (2020–2024)",
    brand: "Skoda", model: "Octavia",
    years: [2020, 2024], body: ["Sedan / Limuzin", "Kombi"], seats: 5, klass: "középkategória",
    picks: [
      { label: "2.0 TDI (150 LE), 2021–2023, manuális vagy DSG", fuel: "Dízel", gearbox: "Manuális",
        price: [8200000, 11500000], km: "60–160 e km",
        why: "A legkiforrottabb VW-dízel a legpraktikusabb karosszériában. Autópályán 5 l/100 km alatt is megy." },
    ],
    why: [
      "Fiatal autó, sok esetben még gyári garanciával vagy annak maradékával — ez a legnagyobb kockázatcsökkentő tényező.",
      "A kombi csomagtartója 640 liter; ez a méret gyakorlatilag mindent visz.",
      "Modern vezetéstámogató rendszerek (adaptív tempomat, sávtartó) alapfelszereltségként sok darabban.",
    ],
    watch: [
      "A korai (2020–2021) darabokban a fedélzeti szoftver és az érintőpanelek bosszantóan hibáztak — kérdezz rá a szoftverfrissítésekre.",
      "A dízel DPF-je városi használatban itt is eltömődik.",
    ],
    avoid: ["1.0 TSI — kevés ehhez az autóhoz, és a hosszú távú terhelés nem tesz jót neki."],
    fit: { városi: 3, hosszútáv: 5, vegyes: 5, család: 5, első: 2 },
    s: { rel: 4, run: 4, comfort: 5, space: 5 },
    tags: ["nagy csomagtartó", "kombi", "hosszú táv", "család", "fiatal autó", "vontatás", "garancia"],
  },
  {
    id: "rav4-5",
    name: "Toyota RAV4 V hibrid (2019–2024)",
    brand: "Toyota", model: "RAV4",
    years: [2019, 2024], body: ["SUV / Terepjáró"], seats: 5, klass: "SUV",
    picks: [
      { label: "2.5 Hybrid AWD-i (222 LE), 2019–2021, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [10500000, 14500000], km: "60–150 e km",
        why: "Erős, csendes, összkerekes családi SUV, ami mégis 6 l/100 km körül fogyaszt. A hibrid hajtáslánc bizonyítottan tartós." },
    ],
    why: [
      "Ez ma az egyik legkeresettebb használt SUV Magyarországon — nem véletlenül: erő, tér, összkerék és alacsony fogyasztás egyben.",
      "Az elektromos hátsó tengely miatt nincs kardán és osztómű, ami elromolhatna — ez hosszú távon sokat számít.",
      "Kiválóan tartja az értékét, tehát a pénzed nagy része megmarad.",
    ],
    watch: [
      "Nagyon keresett típus, ezért az árak magasak és sok a külföldről behozott darab — az eredetiség-ellenőrzés itt különösen fontos.",
      "SoH-mérést itt is kérj, még ha fiatal is az autó.",
    ],
    avoid: ["2.0 benzin (nem hibrid) változat — többet fogyaszt és kevesebbet ér."],
    fit: { városi: 3, hosszútáv: 5, vegyes: 5, család: 5, első: 1 },
    s: { rel: 5, run: 4, comfort: 5, space: 5 },
    tags: ["SUV", "hibrid", "összkerék", "család", "megbízható", "hó", "nagy csomagtartó", "fiatal autó"],
  },
  {
    id: "kodiaq",
    name: "Škoda Kodiaq (2017–2023)",
    brand: "Skoda", model: "Kodiaq",
    years: [2017, 2023], body: ["SUV / Terepjáró"], seats: 7, klass: "nagy SUV",
    picks: [
      { label: "2.0 TDI (150 LE) 4x4, 2019–2021, DSG automata", fuel: "Dízel", gearbox: "Automata",
        price: [9200000, 13500000], km: "80–180 e km",
        why: "Hét ülés, összkerék és kulturált dízel egyben — ez a kombináció ritka és keresett." },
    ],
    why: [
      "Ha 7 ülés kell, de nem akarsz egyterűt, ez a piac egyik legpraktikusabb ajánlata.",
      "A harmadik sor összecsukva óriási, 765 literes csomagtartót ad.",
      "A 4x4 és a dízel párosítás vontatáshoz (lakókocsi, utánfutó, lószállító) kifejezetten erős.",
    ],
    watch: [
      "A DSG (DQ381 nedves kuplungos) váltó olajcseréje kb. 60 e km-enként kötelező — kérj rá dokumentumot.",
      "A harmadik sor felnőttnek szűk; gyereknek viszont teljesen jó.",
      "Nagy autó: városban parkolni és manőverezni tényleg nehézkes.",
    ],
    avoid: ["1.4 / 1.5 TSI benzin ekkora tömeghez — a fogyasztása autópályán rosszabb lesz, mint a dízelé."],
    fit: { városi: 2, hosszútáv: 5, vegyes: 4, család: 5, első: 1 },
    s: { rel: 4, run: 3, comfort: 5, space: 5 },
    tags: ["7 ülés", "SUV", "család", "összkerék", "vontatás", "nagy csomagtartó", "gyerek", "hó"],
  },
  {
    id: "tesla3",
    name: "Tesla Model 3 (2019–2023)",
    brand: "Tesla", model: "Model 3",
    years: [2019, 2023], body: ["Sedan / Limuzin"], seats: 5, klass: "elektromos",
    picks: [
      { label: "Standard Range Plus / Long Range, 2019–2021", fuel: "Elektromos", gearbox: "Automata",
        price: [8800000, 13500000], km: "60–180 e km",
        why: "Reális 350–450 km hatótáv, a Supercharger-hálózat pedig hosszú útra is használhatóvá teszi — ez a legtöbb elektromos autónál nem igaz." },
    ],
    why: [
      "A folyadékhűtött akkumulátor sokkal jobban öregszik, mint a levegőhűtött riválisoké — 150 e km után is jellemzően 90% körüli kapacitás.",
      "Az elektromos hajtáslánc miatt szinte nincs kopó alkatrész: nincs olaj, szíj, kuplung, kipufogó, és a fék is alig kopik.",
      "Ha van otthoni töltésed, a kilométerköltséged a benzines töredéke lesz.",
    ],
    watch: [
      "SoH-mérés és a töltési előzmény (sok gyorstöltés = gyorsabb öregedés) a két kulcskérdés.",
      "A korai (2019-es) darabok összeszerelési minősége egyenetlen: réshézagok, szélzaj, festéshibák — nézd meg élesben.",
      "Magyarországon a márkaszerviz-háttér korlátozott; tájékozódj, hol javítanák.",
    ],
    avoid: ["Performance változat első autónak vagy takarékossági célból — a gumiköltsége jelentős."],
    fit: { városi: 4, hosszútáv: 4, vegyes: 5, család: 4, első: 2 },
    s: { rel: 4, run: 5, comfort: 4, space: 4 },
    tags: ["elektromos", "olcsó fenntartás", "zöld rendszám", "automata", "csendes", "technológia", "gyors"],
  },
  {
    id: "kodiaq-alt-touran",
    name: "Volkswagen Touran III (2015–2023)",
    brand: "Volkswagen", model: "Touran",
    years: [2015, 2023], body: ["Egyterű"], seats: 7, klass: "egyterű",
    picks: [
      { label: "2.0 TDI (150 LE), 2017–2020, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [6400000, 9200000], km: "120–220 e km",
        why: "Hét teljes értékű ülés, kulturált dízel, és a legjobb tér-kihasználás a kategóriában." },
    ],
    why: [
      "Ha tényleg 6–7 ember utazik rendszeresen, egy egyterű praktikusabb, mint egy 7 üléses SUV: könnyebb be- és kiszállni, egyenesebb a tető, jobb a kilátás.",
      "Mind az öt hátsó ülés külön kivehető — költözéskor gyakorlatilag furgon lesz belőle.",
      "Alacsonyabb a fogyasztása és a gumiköltsége, mint egy hasonló méretű SUV-nak.",
    ],
    watch: [
      "A vezérműszíj (kb. 180 e km) és a DSG-váltó olajcsere-története a két kulcskérdés.",
      "A magas tetőn és a nagy üvegfelületen a klíma nyáron erősen dolgozik.",
    ],
    avoid: ["1.2 / 1.4 TSI benzin ekkora tömeghez és ennyi utassal."],
    fit: { városi: 3, hosszútáv: 5, vegyes: 4, család: 5, első: 1 },
    s: { rel: 4, run: 4, comfort: 4, space: 5 },
    tags: ["7 ülés", "család", "gyerek", "nagy csomagtartó", "egyterű", "pakolható"],
  },
  {
    id: "cx5-2",
    name: "Mazda CX-5 II (2017–2023)",
    brand: "Mazda", model: "CX-5",
    years: [2017, 2023], body: ["SUV / Terepjáró"], seats: 5, klass: "SUV",
    picks: [
      { label: "2.0 Skyactiv-G (165 LE), 2018–2021, manuális vagy automata", fuel: "Benzin", gearbox: "Automata",
        price: [7800000, 11500000], km: "70–160 e km",
        why: "Szívó benzines, láncos vezérléssel, klasszikus 6 fokozatú automatával — nincs turbó és nincs dupla kuplungos váltó, ami elromolhatna." },
    ],
    why: [
      "A hagyományos automata váltó (nem DSG, nem CVT) hosszú távon az egyik legmegbízhatóbb megoldás.",
      "Az anyagminőség és a csendesség a prémium márkák szintjét közelíti, jóval kevesebb pénzért.",
      "A szívó motor és a lánc miatt a szervizköltsége kiszámítható.",
    ],
    watch: [
      "A 2.0 benzines városban 9–10 l/100 km-t fogyaszt — nem takarékossági célra való.",
      "A szívószelep-kokszolódás a közvetlen befúvás velejárója; a rendszeres olajcsere a védelem.",
    ],
    avoid: ["2.2 Skyactiv-D dízel rövid, városi utakra — olajhígulás és DPF-eltömődés."],
    fit: { városi: 3, hosszútáv: 5, vegyes: 5, család: 5, első: 2 },
    s: { rel: 4, run: 3, comfort: 5, space: 5 },
    tags: ["SUV", "kényelmes", "csendes", "igényes belső", "automata", "család", "megbízható"],
  },
  {
    id: "kona-e",
    name: "Hyundai Kona Electric / Kia e-Niro (2019–2023)",
    brand: "Hyundai", model: "Kona",
    years: [2019, 2023], body: ["SUV / Terepjáró"], seats: 5, klass: "elektromos SUV",
    picks: [
      { label: "64 kWh elektromos (204 LE), 2019–2021", fuel: "Elektromos", gearbox: "Automata",
        price: [8500000, 12500000], km: "50–140 e km",
        why: "Reális 380–450 km hatótáv folyadékhűtött akkumulátorral, plusz a Hyundai/Kia hosszú akkumulátor-garanciája (8 év / 160 e km)." },
    ],
    why: [
      "Az egyik legjobb hatótáv/ár arány a használt elektromos piacon, és a fogyasztása is kiemelkedően alacsony.",
      "A folyadékhűtött akkumulátor lassabban öregszik, mint a Leaf levegőhűtött csomagja.",
      "Sok darabon még él a gyári akkumulátor-garancia — kérdezz rá, ez pénzben mérhető.",
    ],
    watch: [
      "SoH-mérés és a garancia hátralévő ideje a két kulcskérdés.",
      "A 2020-as visszahívási akció (akkumulátorcsere/szoftver) érintette-e a példányt? Az alvázszám alapján ellenőrizhető.",
    ],
    avoid: ["39 kWh-s alapváltozat, ha néha hosszú útra is mennél."],
    fit: { városi: 5, hosszútáv: 3, vegyes: 5, család: 4, első: 3 },
    s: { rel: 4, run: 5, comfort: 4, space: 3 },
    tags: ["elektromos", "olcsó fenntartás", "zöld rendszám", "automata", "SUV", "garancia", "csendes"],
  },
  {
    id: "bmw3-f30",
    name: "BMW 3-as F30 (2012–2019)",
    brand: "BMW", model: "3",
    years: [2012, 2019], body: ["Sedan / Limuzin", "Kombi"], seats: 5, klass: "prémium közép",
    picks: [
      { label: "320d (B47, 2015 utáni), 2016–2018, automata", fuel: "Dízel", gearbox: "Automata",
        price: [6800000, 9800000], km: "150–250 e km",
        why: "A 2015 utáni B47 dízel megoldotta az elődje (N47) hírhedt vezérműlánc-problémáját. A ZF 8 fokozatú automata pedig az egyik legjobb váltó a piacon." },
    ],
    why: [
      "Ha vezetési élményt keresel prémium környezetben, ebben az árban ez a legjobb ajánlat.",
      "A hátsókerék-hajtás és a kiegyensúlyozott súlyelosztás érezhetően más élményt ad, mint a mezőny.",
      "A ZF 8 fokozatú automata csendes, gyors és megbízható — ha cserélték benne az olajat.",
    ],
    watch: [
      "FONTOS: kizárólag a 2015 utáni B47 motort vedd, a korábbi N47-et NE. Az N47 vezérműlánca a motor hátulján van, és a javításhoz ki kell emelni a motort.",
      "A ZF váltó olajcseréjére kérdezz rá — a BMW „élettartamra\" mondja, a szerelők 80–100 e km-t.",
      "Prémium autó = prémium alkatrészár. Egy futómű-felújítás itt kétszer annyi, mint egy Octaviánál.",
    ],
    avoid: [
      "320d N47 motorral (2012–2015) — a vezérműlánc miatt.",
      "Nagy futású darab dokumentált szerviztörténet nélkül; ennél a márkánál ez különösen kockázatos.",
    ],
    fit: { városi: 3, hosszútáv: 5, vegyes: 4, család: 4, első: 1 },
    s: { rel: 3, run: 2, comfort: 5, space: 4 },
    tags: ["prémium", "jó vezetés", "hosszú táv", "kényelmes", "automata", "gyors"],
  },
  {
    id: "karoq",
    name: "Škoda Karoq (2018–2023)",
    brand: "Skoda", model: "Karoq",
    years: [2018, 2023], body: ["SUV / Terepjáró"], seats: 5, klass: "kompakt SUV",
    picks: [
      { label: "1.5 TSI (150 LE), 2019–2021, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [7200000, 9800000], km: "60–140 e km",
        why: "Erős, kulturált benzines, DPF-gond nélkül — városi és vegyes használatra jobb választás, mint a dízel." },
      { label: "2.0 TDI (150 LE) 4x4, 2019–2021, DSG", fuel: "Dízel", gearbox: "Automata",
        price: [8200000, 11000000], km: "90–180 e km",
        why: "Ha sokat jársz hosszú úton vagy kell az összkerék." },
    ],
    why: [
      "A praktikus Škoda-recept SUV-formában: nagy csomagtartó, jó tér, ésszerű fogyasztás.",
      "A VarioFlex üléspadlós változatban a hátsó ülések külön kivehetők — ilyen rugalmasságot kevés SUV ad.",
      "Fiatal autó, sok esetben még garanciamaradvánnyal.",
    ],
    watch: [
      "A 1.5 TSI-nél SZÍJ van, nem lánc — a csereintervallum határidő, nem javaslat.",
      "A hengerlekapcsolás (ACT) a 1.5 TSI-ben alacsony fordulaton rezonálhat — próbaúton figyeld.",
    ],
    avoid: ["1.0 TSI — kevés ekkora autóhoz, főleg megpakolva."],
    fit: { városi: 4, hosszútáv: 4, vegyes: 5, család: 5, első: 3 },
    s: { rel: 4, run: 4, comfort: 4, space: 5 },
    tags: ["SUV", "család", "nagy csomagtartó", "hasmagasság", "fiatal autó", "pakolható"],
  },

  /* ==================== speciális igények ==================== */
  {
    id: "jogger",
    name: "Dacia Jogger (2022–)",
    brand: "Dacia", model: "Jogger",
    years: [2022, 2026], body: ["Kombi", "Egyterű"], seats: 7, klass: "egyterű",
    picks: [
      { label: "1.0 TCe 110 LPG (Eco-G), 2022–2024, manuális", fuel: "LPG / gáz", gearbox: "Manuális",
        price: [6200000, 8200000], km: "30–90 e km",
        why: "Hét ülés gyári gázüzemmel: a kilométerköltség a benzines feléhez közelít, és a gyári beépítés miatt a garancia is megmarad." },
    ],
    why: [
      "Ez ma a legolcsóbb ÚJ vagy majdnem új hét üléses autó a piacon — nincs is igazi versenytársa ebben az árban.",
      "A gyári LPG (Eco-G) rendszer olcsó üzemeltetést ad úgy, hogy nem utólagos, kétes minőségű beépítés.",
      "Fiatal autó, alacsony km-rel és jellemzően garanciamaradvánnyal.",
    ],
    watch: [
      "Az anyagminőség és a zajszigetelés spórolós — cserébe a fenntartása is az.",
      "A harmadik sor felnőttnek rövid útra jó, hosszúra szűk.",
      "A gázüzem miatt a szelepülékek kopására figyelni kell — kérdezz rá a szervizre.",
    ],
    avoid: ["1.6 hibrid változat, ha az ár a fő szempont — az előnye évek alatt jön vissza."],
    fit: { városi: 3, hosszútáv: 4, vegyes: 5, család: 5, első: 3 },
    s: { rel: 4, run: 5, comfort: 3, space: 5 },
    tags: ["7 ülés", "család", "gyerek", "olcsó fenntartás", "gáz", "fiatal autó", "nagy csomagtartó"],
  },
  {
    id: "s-max",
    name: "Ford S-Max / Galaxy (2015–2022)",
    brand: "Ford", model: "S-Max",
    years: [2015, 2022], body: ["Egyterű"], seats: 7, klass: "egyterű",
    picks: [
      { label: "2.0 TDCi (150/180 LE), 2017–2019, manuális", fuel: "Dízel", gearbox: "Manuális",
        price: [6200000, 9200000], km: "150–250 e km",
        why: "Hét ülés úgy, hogy közben az autó tényleg jól vezethető — ez a kategóriában ritka." },
    ],
    why: [
      "A legjobban vezethető nagy egyterű: a futóműve komoly, mégis kényelmes.",
      "A hét ülés mind teljes értékű, és a második sor három külön ülésből áll (három gyerekülés is elfér).",
      "Nagy autó, autópályára készült — 6 l/100 km körüli reális fogyasztással.",
    ],
    watch: [
      "PowerShift automata változatot kerüld (bár a 2016 utáni 2.0 TDCi-nél már a jobb 6 fokozatú automata is előfordul — ellenőrizd, melyik van benne).",
      "A kétsúlyú lendkerék és a kuplung 180 e km körül tipikus tétel.",
    ],
    avoid: ["1.5 EcoBoost benzin ekkora autóhoz.", "PowerShift (DPS6) váltós darab."],
    fit: { városi: 2, hosszútáv: 5, vegyes: 4, család: 5, első: 1 },
    s: { rel: 3, run: 3, comfort: 5, space: 5 },
    tags: ["7 ülés", "család", "gyerek", "hosszú táv", "jó vezetés", "nagy csomagtartó", "egyterű"],
  },
  {
    id: "up",
    name: "VW Up / Škoda Citigo / Seat Mii (2012–2020)",
    brand: "Volkswagen", model: "Up",
    years: [2012, 2020], body: ["Ferdehátú"], seats: 4, klass: "városi kisautó",
    picks: [
      { label: "1.0 MPI (60/75 LE), 2015–2019, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [2300000, 3600000], km: "60–140 e km",
        why: "A 1.0 MPI szívómotor a VW-csoport egyik legkevesebb bajt okozó egysége: nincs turbó, nincs közvetlen befúvás." },
    ],
    why: [
      "Városi közlekedésre és tanulásra ideális: pici, könnyű parkolni, 5 l/100 km körül fogyaszt.",
      "VW-minőség kisautó-áron, a Citigo/Mii testvérek pedig még olcsóbbak ugyanazért az autóért.",
      "Nagyon kevés elromolható dolog van benne.",
    ],
    watch: [
      "A vezérműszíj (nem lánc!) csereintervalluma kb. 120 e km — kérj rá számlát.",
      "Autópályán zajos és szeles; négy felnőttnek szűk.",
    ],
    avoid: ["ASG robotizált automata változat — lassú és bosszantóan rángat."],
    fit: { városi: 5, hosszútáv: 1, vegyes: 3, család: 1, első: 5 },
    s: { rel: 4, run: 5, comfort: 2, space: 1 },
    tags: ["első autó", "olcsó fenntartás", "könnyű parkolás", "kis fogyasztás", "város"],
  },
  {
    id: "yaris-h",
    name: "Toyota Yaris hibrid (2015–2020)",
    brand: "Toyota", model: "Yaris",
    years: [2015, 2020], body: ["Ferdehátú"], seats: 5, klass: "kisautó",
    picks: [
      { label: "1.5 Hybrid (100 LE), 2017–2020, eCVT automata", fuel: "Hibrid", gearbox: "Automata",
        price: [4400000, 6400000], km: "70–160 e km",
        why: "Városban 4 l/100 km alatt is megy, és a Toyota-hibrid hajtáslánc ebben a méretben is bizonyított." },
    ],
    why: [
      "A legolcsóbban fenntartható városi automata autó: nincs kuplung, nincs váltó, alig kopik a fék.",
      "Ha automata váltót szeretnél, de félsz a DSG-től és a CVT-től, az eCVT itt a biztonságos válasz — ez egy bolygóműves osztó, nem szíjas variátor.",
      "Kis méret, magas megbízhatóság, olcsó biztosítás.",
    ],
    watch: [
      "SoH-mérést itt is kérj.",
      "Négy felnőttnek szűk, és a csomagtartó kicsi.",
    ],
    avoid: ["1.0 benzin változat — takarékos, de városban a hibrid mindenben veri."],
    fit: { városi: 5, hosszútáv: 3, vegyes: 4, család: 2, első: 5 },
    s: { rel: 5, run: 5, comfort: 3, space: 2 },
    tags: ["hibrid", "megbízható", "olcsó fenntartás", "automata", "város", "első autó", "kis fogyasztás"],
  },
  {
    id: "scala",
    name: "Škoda Scala / Seat Leon IV (2019–2023)",
    brand: "Skoda", model: "Scala",
    years: [2019, 2023], body: ["Ferdehátú"], seats: 5, klass: "alsó-közép",
    picks: [
      { label: "1.0 TSI (110 LE), 2020–2022, manuális", fuel: "Benzin", gearbox: "Manuális",
        price: [5600000, 7600000], km: "40–110 e km",
        why: "Fiatal, keveset futott autó garanciamaradvánnyal; a 1.0 TSI ehhez a súlyhoz elég és takarékos." },
    ],
    why: [
      "Ebben az árban ez az egyik legfiatalabb és legkevesebbet futott normális méretű autó — a kevés km hosszú távon többet ér, mint a nagyobb méret.",
      "Meglepően nagy, 467 literes csomagtartó egy kompakt ferdehátúban.",
      "Modern biztonsági és vezetéstámogató rendszerek.",
    ],
    watch: [
      "A 1.0 TSI-nél is SZÍJ van — a csereintervallum betartása kritikus.",
      "Megpakolva, hegyen vagy autópályán a 1.0-s motor dolgozik; ha sokat terhelnéd, a 1.5 TSI a jobb.",
    ],
    avoid: ["DSG7 száraz kuplungos változat városi, dugós használatra."],
    fit: { városi: 4, hosszútáv: 4, vegyes: 5, család: 4, első: 4 },
    s: { rel: 4, run: 4, comfort: 4, space: 4 },
    tags: ["fiatal autó", "kis futás", "garancia", "nagy csomagtartó", "olcsó fenntartás"],
  },
];
